# Generated by Django 3.1.2 on 2020-10-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='Longitude coordinate')),
                ('Y', models.FloatField(help_text='Latitude coordinate')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique squirrel id', max_length=100)),
                ('Shift', models.CharField(blank=True, choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Whether or not the sighting session occurred in the morning or late afternoon', max_length=15)),
                ('Date', models.DateField(blank=True, help_text='Concatenation of the sighting session day and month')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=15, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary fur color', max_length=15, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground plane'), ('Above Ground', 'Above ground')], help_text='location of where the squirrel was when first sighted', max_length=15, null=True)),
                ('Specific_Location', models.TextField(blank=True)),
                ('Running', models.BooleanField(help_text='Whether squirrel was seen running')),
                ('Chasing', models.BooleanField(help_text='Whether squirrel was seen chasing another squirrel')),
                ('Climbing', models.BooleanField(help_text='Whether squirrel was seen climbing a tree or other environmental landmark')),
                ('Eating', models.BooleanField(help_text='Whether squirrel was seen eating')),
                ('Foraging', models.BooleanField(help_text='Whether squirrel was seen foraging for food')),
                ('Other_Activities', models.TextField(blank=True, help_text='Other activities')),
                ('Kuks', models.BooleanField(help_text='Whether squirrel was heard kukking')),
                ('Quaas', models.BooleanField(help_text='Whether squirrel was heard quaaing')),
                ('Moans', models.BooleanField(help_text='Whether squirrel was heard moaning')),
                ('Tail_flags', models.BooleanField(help_text='Whether squirrel was seen flagging its tail')),
                ('Tail_twitches', models.BooleanField(help_text='Whether squirrel was seen twitching its tail')),
                ('Approaches', models.BooleanField(help_text='Whether squirrel was seen approaching human, seeking food')),
                ('Indifferent', models.BooleanField(help_text='Whether squirrel was indifferent to human presence')),
                ('Runs_from', models.BooleanField(help_text='Whether squirrel was seen running from humans, seeing them as a threat')),
            ],
        ),
    ]
