# Generated by Django 3.1.2 on 2020-10-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground plane'), ('Above Ground', 'Above ground')], help_text='Location of where the squirrel was when first sighted', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Other_Activities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Specific squirrel location', max_length=100),
        ),
    ]
