# Generated by Django 3.1.2 on 2020-10-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201016_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Squirrels',
            new_name='Squirrel',
        ),
    ]
