# Generated by Django 3.1.2 on 2020-10-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201016_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(help_text='Whether squirrel was seen running', null=True),
        ),
    ]
