# Generated by Django 3.1.2 on 2020-10-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20201018_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen approaching human, seeking food', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen chasing another squirrel', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen climbing a tree or other environmental landmark', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen eating', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen foraging for food', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was indifferent to human presence', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was heard kukking', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was heard moaning', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was heard quaaing', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen running', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen running from humans, seeing them as a threat', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen flagging its tail', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Whether squirrel was seen twitching its tail', max_length=15, null=True),
        ),
    ]
