# Generated by Django 3.1.2 on 2020-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20201018_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(blank=True, help_text='Concatenation of the sighting session day and month: yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(default=None, help_text='Unique squirrel id', max_length=100, primary_key=True, serialize=False),
        ),
    ]
