# Generated by Django 3.1.2 on 2020-10-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20201019_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique squirrel id', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
