# Generated by Django 3.1.2 on 2020-10-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0008_auto_20201019_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(blank=True, help_text='Concatenation of the sighting session day and month: yyyy-mm-dd', null=True),
        ),
    ]
