# Generated by Django 3.1.2 on 2020-10-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0009_auto_20201019_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='Concatenation of the sighting session day and month: yyyy-mm-dd', null=True),
        ),
    ]
